Repository woowacourse-teams/2022-dallog, pull requests merged in 2023-07, with the labels that each got.

#919 [refactor] ServiceTest의 중첩클래스를 제거한다.
  backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
  backend/src/test/java/com/allog/dallog/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/com/allog/dallog/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/allog/dallog/category/application/CategoryServiceTest.java
  backend/src/test/java/com/allog/dallog/category/application/ExternalCategoryDetailServiceTest.java
  backend/src/test/java/com/allog/dallog/category/presentation/CategoryControllerTest.java
  backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
  backend/src/test/java/com/allog/dallog/common/annotation/ControllerTest.java
  backend/src/test/java/com/allog/dallog/common/annotation/RepositoryTest.java
  backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
  backend/src/test/java/com/allog/dallog/common/builder/BuilderSupporter.java
  backend/src/test/java/com/allog/dallog/common/builder/GivenBuilder.java
  backend/src/test/java/com/allog/dallog/externalcalendar/application/ExternalCalendarServiceTest.java
  backend/src/test/java/com/allog/dallog/externalcalendar/presentation/ExternalCalendarControllerTest.java
  backend/src/test/java/com/allog/dallog/infrastructure/oauth/client/StubOAuthClient.java
  backend/src/test/java/com/allog/dallog/member/application/MemberServiceTest.java
  backend/src/test/java/com/allog/dallog/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/allog/dallog/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/com/allog/dallog/schedule/presentation/ScheduleControllerTest.java
  backend/src/test/java/com/allog/dallog/subscription/application/SubscriptionServiceTest.java
  backend/src/test/java/com/allog/dallog/subscription/presentation/SubscriptionControllerTest.java
Labels: backend, refactor, test

#934 [chore] 라이센스 추가
  LICENSE
Labels: chore

#935 [refactor] BaseEntity package 구조 변경
  backend/src/main/java/com/allog/dallog/auth/domain/OAuthToken.java
  backend/src/main/java/com/allog/dallog/category/domain/Category.java
  backend/src/main/java/com/allog/dallog/category/domain/ExternalCategoryDetail.java
  backend/src/main/java/com/allog/dallog/categoryrole/domain/CategoryRole.java
  backend/src/main/java/com/allog/dallog/global/entity/BaseEntity.java
  backend/src/main/java/com/allog/dallog/member/domain/Member.java
  backend/src/main/java/com/allog/dallog/schedule/domain/Schedule.java
  backend/src/main/java/com/allog/dallog/subscription/domain/Subscription.java
Labels: refactor, chore
